// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"de_DE": &dictionary{index: de_DEIndex, data: de_DEData},
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
		"es_ES": &dictionary{index: es_ESIndex, data: es_ESData},
		"fr_FR": &dictionary{index: fr_FRIndex, data: fr_FRData},
		"it_IT": &dictionary{index: it_ITIndex, data: it_ITData},
		"ja_JP": &dictionary{index: ja_JPIndex, data: ja_JPData},
		"ko_KR": &dictionary{index: ko_KRIndex, data: ko_KRData},
		"pt_BR": &dictionary{index: pt_BRIndex, data: pt_BRData},
		"ru_RU": &dictionary{index: ru_RUIndex, data: ru_RUData},
		"zh_CN": &dictionary{index: zh_CNIndex, data: zh_CNData},
		"zh_TW": &dictionary{index: zh_TWIndex, data: zh_TWData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"\t\tor": 213,
	"\tIf not, download desktop engine from:":                                                                212,
	"%q is not a valid URL for --using flag":                                                                 203,
	"%s Error occurred while opening or operating on file %s (Reason: %s).":                                  9,
	"%s Specifies the instance of SQL Server to which to connect. It sets the sqlcmd scripting variable %s.": 245,
	"%sSyntax error at line %d":                                                                              10,
	"%v":                                                                                                     56,
	"'%s %s': Unexpected argument. Argument value has to be %v.":                                             273,
	"'%s %s': Unexpected argument. Argument value has to be one of %v.":                                      274,
	"'%s %s': value must be greater than %#v and less than %#v.":                                             272,
	"'%s %s': value must be greater than or equal to %#v and less than or equal to %#v.":                     271,
	"'%s' scripting variable not defined.":                                                                   6,
	"'%s': Missing argument. Enter '-?' for help.":                                                           276,
	"'%s': Unknown Option. Enter '-?' for help.":                                                             277,
	"'-a %#v': Packet size has to be a number between 512 and 32767.":                                        228,
	"'-h %#v': header value must be either -1 or a value between 1 and 2147483647":                           0,
	"--user-database %q contains non-ASCII chars and/or quotes":                                              192,
	"--using URL must be http or https":                                                                      202,
	"--using URL must have a path to .bak file":                                                              204,
	"--using file URL must be a .bak file":                                                                   205,
	"-? shows this syntax summary, %s shows modern sqlcmd sub-command help":                                  234,
	"Accept the SQL Server EULA":                                                                             175,
	"Add a context":                                                                                          61,
	"Add a context for a local instance of SQL Server on port 1433 using trusted authentication":             62,
	"Add a context for this endpoint":                                                                        82,
	"Add a context manually":                                                                                 47,
	"Add a default endpoint":                                                                                 78,
	"Add a new local endpoint":                                                                               67,
	"Add a user":                                                                                             91,
	"Add a user (using the SQLCMDPASSWORD environment variable)":                                             89,
	"Add a user (using the SQLCMD_PASSWORD environment variable)":                                            88,
	"Add a user using Windows Data Protection API to encrypt password in sqlconfig":                          90,
	"Add an already existing endpoint":                                                                       68,
	"Add an endpoint":                                                                                        72,
	"Add context for existing endpoint and user (use %s or %s)":                                              19,
	"Add the %s flag":                                                                                        101,
	"Add the user":                                                                                           71,
	"Authentication Type '%s' requires a password":                                                           104,
	"Authentication type '' is not valid %v'":                                                                97,
	"Authentication type must be '%s' or '%s'":                                                               96,
	"Authentication type this user will use (basic | other)":                                                 93,
	"Both environment variables %s and %s are set. ":                                                         110,
	"Causes sqlcmd to ignore scripting variables. This parameter is useful when a script contains many %s statements that may contain strings that have the same format as regular variables, such as $(variable_name)": 249,
	"Change current context": 197,
	"Command text to run":    26,
	"Complete the operation even if non-system (user) database files are present":      43,
	"Connection Strings only supported for %s Auth type":                               115,
	"Container %q no longer exists, continuing to remove context...":                   54,
	"Container is not running, unable to verify that user database files do not exist": 52,
	"Context '%v' deleted":        123,
	"Context '%v' does not exist": 124,
	"Context name (a default context name will be created if not provided)":                                                            173,
	"Context name to view details of":                                                                                                  141,
	"Controls the severity level that is used to set the %s variable on exit":                                                          267,
	"Controls which error messages are sent to %s. Messages that have severity level greater than or equal to this level are sent":     260,
	"Controls which error messages are sent to stdout. Messages that have severity level greater than or equal to this level are sent": 257,
	"Create SQL Server with an empty user database":                                                                                    222,
	"Create SQL Server, download and attach AdventureWorks sample database":                                                            220,
	"Create SQL Server, download and attach AdventureWorks sample database with different database name":                               221,
	"Create a new context with a SQL Server container ":                                                                                38,
	"Create a user database and set it as the default for login":                                                                       174,
	"Create context": 45,
	"Create context with SQL Server container":                  46,
	"Create new context with a sql container ":                  33,
	"Created context %q in \"%s\", configuring user account...": 194,
	"Creates a sqlcmd scripting variable that can be used in a sqlcmd script. Enclose the value in quotation marks if the value contains spaces. You can specify multiple var=values values. If there are errors in any of the values specified, sqlcmd generates an error message and then exits": 250,
	"Creating default database [%s]":                                             207,
	"Current Context '%v'":                                                       77,
	"Current context does not have a container":                                  34,
	"Current context is %q. Do you want to continue? (Y/N)":                      48,
	"Current context is now %s":                                                  55,
	"Database for the connection string (default is taken from the T/SQL login)": 114,
	"Database to use":                                                            27,
	"Declares the application workload type when connecting to a server. The only currently supported value is ReadOnly. If %s is not specified, the sqlcmd utility will not support connectivity to a secondary replica in an Always On availability group": 254,
	"Dedicated administrator connection":                              269,
	"Delete a context":                                                117,
	"Delete a context (excluding its endpoint and user)":              119,
	"Delete a context (including its endpoint and user)":              118,
	"Delete a user":                                                   131,
	"Delete an endpoint":                                              125,
	"Delete the context's endpoint and user as well":                  121,
	"Delete this endpoint":                                            86,
	"Describe one context in your sqlconfig file":                     140,
	"Describe one endpoint in your sqlconfig file":                    147,
	"Describe one user in your sqlconfig file":                        154,
	"Disabled %q account (and rotated %q password). Creating user %q": 195,
	"Disables commands that might compromise system security. Sqlcmd issues a warning and continues": 246,
	"Display connections strings for the current context":                                            112,
	"Display merged sqlconfig settings or a specified sqlconfig file":                                166,
	"Display name for the context":                                                                   63,
	"Display name for the endpoint":                                                                  79,
	"Display name for the user (this is not the username)":                                           92,
	"Display one or many contexts from the sqlconfig file":                                           137,
	"Display one or many endpoints from the sqlconfig file":                                          145,
	"Display one or many users from the sqlconfig file":                                              152,
	"Display raw byte data":                                                                          169,
	"Display the current-context":                                                                    116,
	"Don't download image.  Use already downloaded image":                                            181,
	"Download (into container) and attach database (.bak) from URL":                                  188,
	"Downloading %s": 208,
	"Downloading %v": 210,
	"ED and !!<command> commands, startup script, and environment variables are disabled": 4,
	"EULA not accepted":                                                             191,
	"Either, add the %s flag to the command-line":                                   189,
	"Encryption method '%v' is not valid":                                           108,
	"Endpoint '%v' added (address: '%v', port: '%v')":                               87,
	"Endpoint '%v' deleted":                                                         130,
	"Endpoint '%v' does not exist":                                                  129,
	"Endpoint name must be provided.  Provide endpoint name with %s flag":           127,
	"Endpoint name to view details of":                                              148,
	"Endpoint required to add context.  Endpoint '%v' does not exist.  Use %s flag": 69,
	"Executes a query when sqlcmd starts and then immediately exits sqlcmd. Multiple-semicolon-delimited queries can be executed":                             244,
	"Executes a query when sqlcmd starts, but does not exit sqlcmd when the query has finished running. Multiple-semicolon-delimited queries can be executed": 243,
	"Explicitly set the container hostname, it defaults to the container ID":                                                                                  184,
	"File does not exist at URL": 216,
	"Flags:":                     233,
	"Generated password length":  176,
	"Get tags available for Azure SQL Edge install": 224,
	"Get tags available for mssql install":          226,
	"Identifies one or more files that contain batches of SQL statements. If one or more files do not exist, sqlcmd will exit. Mutually exclusive with %s/%s": 235,
	"Identifies the file that receives output from sqlcmd":                      236,
	"If the database is mounted, run %s":                                        57,
	"Implicitly trust the server certificate without validation":                238,
	"Include context details":                                                   142,
	"Include endpoint details":                                                  149,
	"Include user details":                                                      156,
	"Install Azure Sql Edge":                                                    170,
	"Install/Create Azure SQL Edge in a container":                              171,
	"Install/Create SQL Server in a container":                                  218,
	"Install/Create SQL Server with full logging":                               223,
	"Install/Create SQL Server, Azure SQL, and Tools":                           20,
	"Install/Create, Query, Uninstall SQL Server":                               11,
	"Invalid --using file type":                                                 206,
	"Invalid variable identifier %s":                                            278,
	"Invalid variable value %s":                                                 279,
	"Is a container runtime installed on this machine (e.g. Podman or Docker)?": 211,
	"Is a container runtime running?  (Try `%s` or `%s` (list containers), does it return without error?)": 214,
	"Legal docs and information: aka.ms/SqlcmdLegal":                                                       230,
	"Level of mssql driver messages to print":                                                              258,
	"Line in errorlog to wait for before connecting":                                                       182,
	"List all the context names in your sqlconfig file":                                                    138,
	"List all the contexts in your sqlconfig file":                                                         139,
	"List all the endpoints in your sqlconfig file":                                                        146,
	"List all the users in your sqlconfig file":                                                            153,
	"List connection strings for all client drivers":                                                       113,
	"List tags":                                              225,
	"Minimum number of numeric characters":                   178,
	"Minimum number of special characters":                   177,
	"Minimum number of upper characters":                     179,
	"Modify sqlconfig files using subcommands like \"%s\"":   18,
	"Name of context to delete":                              120,
	"Name of context to set as current context":              161,
	"Name of endpoint this context will use":                 64,
	"Name of endpoint to delete":                             126,
	"Name of user this context will use":                     65,
	"Name of user to delete":                                 132,
	"No context exists with the name: \"%v\"":                165,
	"No current context":                                     31,
	"No endpoints to uninstall":                              60,
	"Now ready for client connections on port %d":            201,
	"Open in Azure Data Studio":                              74,
	"Open tools (e.g Azure Data Studio) for current context": 21,
	"Or, set the environment variable i.e. %s %s=YES ":       190,
	"Pass in the %s %s":                                      99,
	"Pass in the flag %s to override this safety check for user (non-system) databases": 58,
	"Password": 266,
	"Password encryption method (%s) in sqlconfig file":                                                                      95,
	"Port (next available port from 1433 upwards used by default)":                                                           187,
	"Print version information and exit":                                                                                     237,
	"Provide a username with the %s flag":                                                                                    105,
	"Provide a valid encryption method (%s) with the %s flag":                                                                107,
	"Provide password in the %s (or %s) environment variable":                                                                103,
	"Provided for backward compatibility. Sqlcmd always optimizes detection of the active replica of a SQL Failover Cluster": 265,
	"Quiet mode (do not stop for user input to confirm the operation)":                                                       42,
	"Remove":                               200,
	"Remove the %s flag":                   98,
	"Remove trailing spaces from a column": 264,
	"Removing context %s":                  53,
	"Requests a packet of a different size. This option sets the sqlcmd scripting variable %s. packet_size must be a value between 512 and 32767. The default = 4096. A larger packet size can enhance performance for execution of scripts that have lots of SQL statements between %s commands. You can request a larger packet size. However, if the request is denied, sqlcmd uses the server default for packet size": 251,
	"Restoring database %s":                                         209,
	"Run a query":                                                   23,
	"Run a query against the current context":                       22,
	"Run a query using [%s] database":                               24,
	"See all release tags for SQL Server, install previous version": 219,
	"See connection strings":                                        199,
	"Servers:":                                                      229,
	"Set new default database":                                      25,
	"Set the current context":                                       159,
	"Set the mssql context (endpoint/user) to be the current context":         160,
	"Sets the sqlcmd scripting variable %s":                                   270,
	"Show sqlconfig settings and raw authentication data":                     168,
	"Show sqlconfig settings, with REDACTED authentication data":              167,
	"Special character set to include in password":                            180,
	"Specifies that all output files are encoded with little-endian Unicode":  262,
	"Specifies that sqlcmd exits and returns a %s value when an error occurs": 259,
	"Specifies the SQL authentication method to use to connect to Azure SQL Database. One of: ActiveDirectoryDefault, ActiveDirectoryIntegrated, ActiveDirectoryPassword, ActiveDirectoryInteractive, ActiveDirectoryManagedIdentity, ActiveDirectoryServicePrincipal, SqlPassword": 247,
	"Specifies the batch terminator. The default value is %s":         241,
	"Specifies the column separator character. Sets the %s variable.": 263,
	"Specifies the formatting for results":                            256,
	"Specifies the image CPU architecture":                            185,
	"Specifies the image operating system":                            186,
	"Specifies the number of rows to print between the column headings. Use -h-1 to specify that headers not be printed":                                                                                                         261,
	"Specifies the number of seconds before a sqlcmd login to the go-mssqldb driver times out when you try to connect to a server. This option sets the sqlcmd scripting variable %s. The default value is 30. 0 means infinite": 252,
	"Specifies the screen width for output":                                        268,
	"Specify a custom name for the container rather than a randomly generated one": 183,
	"Sqlcmd: Error: ":                              2,
	"Sqlcmd: Warning: ":                            3,
	"Start current context":                        28,
	"Start interactive session":                    196,
	"Start the current context":                    29,
	"Starting %q for context %q":                   32,
	"Starting %v":                                  193,
	"Stop current context":                         35,
	"Stop the current context":                     36,
	"Stopping %q for context %q":                   37,
	"Switched to context \"%v\".":                  164,
	"Syntax error at line %d near command '%s'.":   8,
	"Tag to use, use get-tags to see list of tags": 172,
	"Tells sqlcmd to use ActiveDirectory authentication. If no user name is provided, authentication method ActiveDirectoryDefault is used. If a password is provided, ActiveDirectoryPassword is used. Otherwise ActiveDirectoryInteractive is used": 248,
	"The %s and the %s options are mutually exclusive.":                                                                        275,
	"The %s flag can only be used when authentication type is '%s'":                                                            100,
	"The %s flag must be set when authentication type is '%s'":                                                                 102,
	"The -L parameter can not be used in combination with other parameters.":                                                   227,
	"The environment variable: '%s' has invalid value: '%s'.":                                                                  7,
	"The login name or contained database user name.  For contained database users, you must provide the database name option": 242,
	"The network address to connect to, e.g. 127.0.0.1 etc.":                                                                   80,
	"The network port to connect to, e.g. 1433 etc.":                                                                           81,
	"The scripting variable: '%s' is read-only":                                                                                5,
	"The username (provide password in %s or %s environment variable)":                                                         94,
	"Third party notices: aka.ms/SqlcmdNotices":                                                                                231,
	"This option sets the sqlcmd scripting variable %s. The workstation name is listed in the hostname column of the sys.sysprocesses catalog view and can be returned using the stored procedure sp_who. If this option is not specified, the default is the current computer name. This name can be used to identify different sqlcmd sessions": 253,
	"This option sets the sqlcmd scripting variable %s. This parameter specifies the initial database. The default is your login's default-database property. If the database does not exist, an error message is generated and sqlcmd exits":                                                                                                     239,
	"This switch is used by the client to request an encrypted connection": 255,
	"To override the check, use %s":                                        51,
	"To remove:         %s":                                                163,
	"To run a query":                                                       76,
	"To run a query:    %s":                                                162,
	"To start interactive query session":                                   75,
	"To start the container":                                               50,
	"To view available contexts":                                           30,
	"To view available contexts run `%s`":                                  143,
	"To view available endpoints run `%s`":                                 150,
	"To view available users run `%s`":                                     157,
	"Unable to continue, a user (non-system) database (%s) is present":     59,
	"Unable to download file":                                              217,
	"Unable to download image %s":                                          215,
	"Uninstall/Delete the current context":                                 39,
	"Uninstall/Delete the current context, no user prompt":                 40,
	"Uninstall/Delete the current context, no user prompt and override safety check for user databases": 41,
	"Unset one of the environment variables %s or %s":                                                   109,
	"Use the %s flag to pass in a context name to delete":                                               122,
	"User %q deleted":          136,
	"User %q does not exist":   135,
	"User '%v' added":          111,
	"User '%v' does not exist": 73,
	"User name must be provided.  Provide user name with %s flag": 133,
	"User name to view details of":                                155,
	"Username not provided":                                       106,
	"Uses a trusted connection instead of using a user name and password to sign in to SQL Server, ignoring any environment variables that define user name and password": 240,
	"Verifying no user (non-system) database (.mdf) files": 49,
	"Version %v\n":               232,
	"View all endpoints details": 85,
	"View available contexts":    44,
	"View configuration information and connection strings":    12,
	"View endpoint details":                                    84,
	"View endpoint names":                                      83,
	"View endpoints":                                           128,
	"View existing endpoints to choose from":                   66,
	"View list of users":                                       70,
	"View sqlcmd configuration":                                198,
	"View users":                                               134,
	"configuration file":                                       16,
	"error: no context exists with the name: \"%v\"":           144,
	"error: no endpoint exists with the name: \"%v\"":          151,
	"error: no user exists with the name: \"%v\"":              158,
	"help for backwards compatibility flags (-S, -U, -E etc.)": 14,
	"invalid batch terminator '%s'":                            1,
	"log level, error=0, warn=1, info=2, debug=3, trace=4":     17,
	"print version of sqlcmd":                                  15,
	"sqlcmd: Install/Create/Query SQL Server, Azure SQL, and Tools\n\nFeedback:\n  %s": 13,
}

var de_DEIndex = []uint32{ // 281 elements
	// Entry 0 - 1F
	0x00000000, 0x0000005b, 0x00000085, 0x0000009a,
	0x000000b0, 0x00000104, 0x00000135, 0x00000165,
	0x000001af, 0x000001ec, 0x00000239, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	// Entry 20 - 3F
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	// Entry 40 - 5F
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	// Entry 60 - 7F
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	// Entry 80 - 9F
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	// Entry A0 - BF
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	// Entry C0 - DF
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	// Entry E0 - FF
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	// Entry 100 - 11F
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a, 0x0000025a, 0x0000025a, 0x0000025a,
	0x0000025a,
} // Size: 1148 bytes

const de_DEData string = "" + // Size: 602 bytes
	"\x02'-h %#[1]v': Der Headerwert muss entweder -1 oder ein Wert zwischen " +
	"-1 und 2147483647 sein\x02Ungültiges Batchabschlusszeichen '%[1]s'\x04" +
	"\x00\x01 \x10\x02Sqlcmd: Fehler:\x04\x00\x01 \x11\x02Sqlcmd: Warnung:" +
	"\x02Die Befehle ED und !!<command>, Startskript und Umgebungsvariablen s" +
	"ind deaktiviert\x02Die '%[1]s'-Skriptvariable ist schreibgeschützt\x02Di" +
	"e '%[1]s'-Skriptvariable ist nicht definiert.\x02Die Umgebungsvariable: " +
	"'%[1]s' weist einen ungültigen Wert auf: '%[2]s'.\x02Syntaxfehler in Zei" +
	"le %[1]d in der Nähe von Befehl '%[2]s'.\x02%[1]s Fehler beim Öffnen ode" +
	"r Verarbeiten von Datei %[2]s (Ursache: %[3]s).\x02%[1]sSyntaxfehler in " +
	"Zeile %[2]d"

var en_USIndex = []uint32{ // 281 elements
	// Entry 0 - 1F
	0x00000000, 0x00000050, 0x00000071, 0x00000085,
	0x0000009b, 0x000000ef, 0x0000011c, 0x00000144,
	0x00000182, 0x000001b3, 0x00000202, 0x00000222,
	0x0000024e, 0x00000284, 0x000002d5, 0x0000030e,
	0x00000326, 0x00000339, 0x0000036e, 0x000003a4,
	0x000003e4, 0x00000414, 0x0000044b, 0x00000473,
	0x0000047f, 0x000004a2, 0x000004bb, 0x000004cf,
	0x000004df, 0x000004f5, 0x0000050f, 0x0000052a,
	// Entry 20 - 3F
	0x0000053d, 0x0000055e, 0x0000058b, 0x000005b5,
	0x000005ca, 0x000005e3, 0x00000604, 0x0000063a,
	0x0000065f, 0x00000694, 0x000006f6, 0x00000737,
	0x00000783, 0x0000079b, 0x000007aa, 0x000007d3,
	0x000007ea, 0x00000823, 0x00000858, 0x0000086f,
	0x00000890, 0x000008e1, 0x000008f8, 0x0000093a,
	0x00000957, 0x0000095d, 0x00000983, 0x000009d8,
	0x00000a1c, 0x00000a36, 0x00000a44, 0x00000a9f,
	// Entry 40 - 5F
	0x00000abc, 0x00000ae3, 0x00000b06, 0x00000b2d,
	0x00000b46, 0x00000b67, 0x00000bbb, 0x00000bce,
	0x00000bdb, 0x00000beb, 0x00000c07, 0x00000c21,
	0x00000c44, 0x00000c53, 0x00000c6b, 0x00000c82,
	0x00000ca0, 0x00000cd7, 0x00000d06, 0x00000d26,
	0x00000d3a, 0x00000d50, 0x00000d6b, 0x00000d80,
	0x00000db9, 0x00000df5, 0x00000e30, 0x00000e7e,
	0x00000e89, 0x00000ebe, 0x00000ef5, 0x00000f3c,
	// Entry 60 - 7F
	0x00000f71, 0x00000fa0, 0x00000fcb, 0x00000fe1,
	0x00000ff9, 0x0000103d, 0x00001050, 0x0000108f,
	0x000010cd, 0x000010fd, 0x00001124, 0x0000113a,
	0x00001178, 0x0000119f, 0x000011d5, 0x0000120e,
	0x00001221, 0x00001255, 0x00001284, 0x000012cf,
	0x00001305, 0x00001321, 0x00001332, 0x00001365,
	0x00001398, 0x000013b2, 0x000013e1, 0x00001418,
	0x00001430, 0x0000144f, 0x00001462, 0x0000147d,
	// Entry 80 - 9F
	0x000014c4, 0x000014d3, 0x000014f3, 0x0000150c,
	0x0000151a, 0x00001531, 0x00001570, 0x0000157b,
	0x00001595, 0x000015a8, 0x000015dd, 0x0000160f,
	0x0000163c, 0x00001668, 0x00001688, 0x000016a0,
	0x000016c7, 0x000016f7, 0x0000172d, 0x0000175b,
	0x00001788, 0x000017a9, 0x000017c2, 0x000017ea,
	0x0000181b, 0x0000184d, 0x00001877, 0x000018a0,
	0x000018bd, 0x000018d2, 0x000018f6, 0x00001923,
	// Entry A0 - BF
	0x0000193b, 0x0000197b, 0x000019a5, 0x000019be,
	0x000019d7, 0x000019f4, 0x00001a1d, 0x00001a5d,
	0x00001a98, 0x00001acc, 0x00001ae2, 0x00001af9,
	0x00001b26, 0x00001b53, 0x00001b99, 0x00001bd4,
	0x00001bef, 0x00001c09, 0x00001c2e, 0x00001c53,
	0x00001c76, 0x00001ca3, 0x00001cd7, 0x00001d06,
	0x00001d53, 0x00001d9a, 0x00001dbf, 0x00001de4,
	0x00001e21, 0x00001e5f, 0x00001e8e, 0x00001ec9,
	// Entry C0 - DF
	0x00001edb, 0x00001f18, 0x00001f27, 0x00001f65,
	0x00001fae, 0x00001fc8, 0x00001fdf, 0x00001ff9,
	0x00002010, 0x00002017, 0x00002046, 0x00002068,
	0x00002092, 0x000020bc, 0x000020e1, 0x000020fb,
	0x0000211d, 0x0000212f, 0x00002148, 0x0000215a,
	0x000021a4, 0x000021cf, 0x000021d8, 0x00002243,
	0x00002262, 0x0000227d, 0x00002295, 0x000022be,
	0x000022fc, 0x00002342, 0x000023a5, 0x000023d3,
	// Entry E0 - FF
	0x000023ff, 0x0000242d, 0x00002437, 0x0000245c,
	0x000024a3, 0x000024e6, 0x000024ef, 0x0000251e,
	0x00002548, 0x0000255b, 0x00002562, 0x000025ab,
	0x00002649, 0x0000267e, 0x000026a1, 0x000026dc,
	0x000027c7, 0x0000286b, 0x000028a6, 0x0000291f,
	0x000029b7, 0x00002a33, 0x00002aa0, 0x00002aff,
	0x00002c0d, 0x00002cfd, 0x00002dd2, 0x00002eef,
	0x0000308a, 0x00003168, 0x000032b7, 0x000033b1,
	// Entry 100 - 11F
	0x000033f6, 0x0000341b, 0x0000349c, 0x000034c4,
	0x0000350f, 0x0000358f, 0x00003602, 0x00003649,
	0x0000368c, 0x000036b1, 0x00003728, 0x00003731,
	0x0000377c, 0x000037a2, 0x000037c5, 0x000037ee,
	0x0000384d, 0x00003894, 0x000038d8, 0x00003923,
	0x0000395b, 0x0000398b, 0x000039b9, 0x000039db,
	0x000039f8,
} // Size: 1148 bytes

const en_USData string = "" + // Size: 14840 bytes
	"\x02'-h %#[1]v': header value must be either -1 or a value between 1 and" +
	" 2147483647\x02invalid batch terminator '%[1]s'\x04\x00\x01 \x0f\x02Sqlc" +
	"md: Error:\x04\x00\x01 \x11\x02Sqlcmd: Warning:\x02ED and !!<command> co" +
	"mmands, startup script, and environment variables are disabled\x02The sc" +
	"ripting variable: '%[1]s' is read-only\x02'%[1]s' scripting variable not" +
	" defined.\x02The environment variable: '%[1]s' has invalid value: '%[2]s" +
	"'.\x02Syntax error at line %[1]d near command '%[2]s'.\x02%[1]s Error oc" +
	"curred while opening or operating on file %[2]s (Reason: %[3]s).\x02%[1]" +
	"sSyntax error at line %[2]d\x02Install/Create, Query, Uninstall SQL Serv" +
	"er\x02View configuration information and connection strings\x02sqlcmd: I" +
	"nstall/Create/Query SQL Server, Azure SQL, and Tools\x0a\x0aFeedback:" +
	"\x0a  %[1]s\x02help for backwards compatibility flags (-S, -U, -E etc.)" +
	"\x02print version of sqlcmd\x02configuration file\x02log level, error=0," +
	" warn=1, info=2, debug=3, trace=4\x02Modify sqlconfig files using subcom" +
	"mands like \x22%[1]s\x22\x02Add context for existing endpoint and user (" +
	"use %[1]s or %[2]s)\x02Install/Create SQL Server, Azure SQL, and Tools" +
	"\x02Open tools (e.g Azure Data Studio) for current context\x02Run a quer" +
	"y against the current context\x02Run a query\x02Run a query using [%[1]s" +
	"] database\x02Set new default database\x02Command text to run\x02Databas" +
	"e to use\x02Start current context\x02Start the current context\x02To vie" +
	"w available contexts\x02No current context\x02Starting %[1]q for context" +
	" %[2]q\x04\x00\x01 (\x02Create new context with a sql container\x02Curre" +
	"nt context does not have a container\x02Stop current context\x02Stop the" +
	" current context\x02Stopping %[1]q for context %[2]q\x04\x00\x01 1\x02Cr" +
	"eate a new context with a SQL Server container\x02Uninstall/Delete the c" +
	"urrent context\x02Uninstall/Delete the current context, no user prompt" +
	"\x02Uninstall/Delete the current context, no user prompt and override sa" +
	"fety check for user databases\x02Quiet mode (do not stop for user input " +
	"to confirm the operation)\x02Complete the operation even if non-system (" +
	"user) database files are present\x02View available contexts\x02Create co" +
	"ntext\x02Create context with SQL Server container\x02Add a context manua" +
	"lly\x02Current context is %[1]q. Do you want to continue? (Y/N)\x02Verif" +
	"ying no user (non-system) database (.mdf) files\x02To start the containe" +
	"r\x02To override the check, use %[1]s\x02Container is not running, unabl" +
	"e to verify that user database files do not exist\x02Removing context %[" +
	"1]s\x02Container %[1]q no longer exists, continuing to remove context..." +
	"\x02Current context is now %[1]s\x02%[1]v\x02If the database is mounted," +
	" run %[1]s\x02Pass in the flag %[1]s to override this safety check for u" +
	"ser (non-system) databases\x02Unable to continue, a user (non-system) da" +
	"tabase (%[1]s) is present\x02No endpoints to uninstall\x02Add a context" +
	"\x02Add a context for a local instance of SQL Server on port 1433 using " +
	"trusted authentication\x02Display name for the context\x02Name of endpoi" +
	"nt this context will use\x02Name of user this context will use\x02View e" +
	"xisting endpoints to choose from\x02Add a new local endpoint\x02Add an a" +
	"lready existing endpoint\x02Endpoint required to add context.  Endpoint " +
	"'%[1]v' does not exist.  Use %[2]s flag\x02View list of users\x02Add the" +
	" user\x02Add an endpoint\x02User '%[1]v' does not exist\x02Open in Azure" +
	" Data Studio\x02To start interactive query session\x02To run a query\x02" +
	"Current Context '%[1]v'\x02Add a default endpoint\x02Display name for th" +
	"e endpoint\x02The network address to connect to, e.g. 127.0.0.1 etc.\x02" +
	"The network port to connect to, e.g. 1433 etc.\x02Add a context for this" +
	" endpoint\x02View endpoint names\x02View endpoint details\x02View all en" +
	"dpoints details\x02Delete this endpoint\x02Endpoint '%[1]v' added (addre" +
	"ss: '%[2]v', port: '%[3]v')\x02Add a user (using the SQLCMD_PASSWORD env" +
	"ironment variable)\x02Add a user (using the SQLCMDPASSWORD environment v" +
	"ariable)\x02Add a user using Windows Data Protection API to encrypt pass" +
	"word in sqlconfig\x02Add a user\x02Display name for the user (this is no" +
	"t the username)\x02Authentication type this user will use (basic | other" +
	")\x02The username (provide password in %[1]s or %[2]s environment variab" +
	"le)\x02Password encryption method (%[1]s) in sqlconfig file\x02Authentic" +
	"ation type must be '%[1]s' or '%[2]s'\x02Authentication type '' is not v" +
	"alid %[1]v'\x02Remove the %[1]s flag\x02Pass in the %[1]s %[2]s\x02The %" +
	"[1]s flag can only be used when authentication type is '%[2]s'\x02Add th" +
	"e %[1]s flag\x02The %[1]s flag must be set when authentication type is '" +
	"%[2]s'\x02Provide password in the %[1]s (or %[2]s) environment variable" +
	"\x02Authentication Type '%[1]s' requires a password\x02Provide a usernam" +
	"e with the %[1]s flag\x02Username not provided\x02Provide a valid encryp" +
	"tion method (%[1]s) with the %[2]s flag\x02Encryption method '%[1]v' is " +
	"not valid\x02Unset one of the environment variables %[1]s or %[2]s\x04" +
	"\x00\x01 4\x02Both environment variables %[1]s and %[2]s are set.\x02Use" +
	"r '%[1]v' added\x02Display connections strings for the current context" +
	"\x02List connection strings for all client drivers\x02Database for the c" +
	"onnection string (default is taken from the T/SQL login)\x02Connection S" +
	"trings only supported for %[1]s Auth type\x02Display the current-context" +
	"\x02Delete a context\x02Delete a context (including its endpoint and use" +
	"r)\x02Delete a context (excluding its endpoint and user)\x02Name of cont" +
	"ext to delete\x02Delete the context's endpoint and user as well\x02Use t" +
	"he %[1]s flag to pass in a context name to delete\x02Context '%[1]v' del" +
	"eted\x02Context '%[1]v' does not exist\x02Delete an endpoint\x02Name of " +
	"endpoint to delete\x02Endpoint name must be provided.  Provide endpoint " +
	"name with %[1]s flag\x02View endpoints\x02Endpoint '%[1]v' does not exis" +
	"t\x02Endpoint '%[1]v' deleted\x02Delete a user\x02Name of user to delete" +
	"\x02User name must be provided.  Provide user name with %[1]s flag\x02Vi" +
	"ew users\x02User %[1]q does not exist\x02User %[1]q deleted\x02Display o" +
	"ne or many contexts from the sqlconfig file\x02List all the context name" +
	"s in your sqlconfig file\x02List all the contexts in your sqlconfig file" +
	"\x02Describe one context in your sqlconfig file\x02Context name to view " +
	"details of\x02Include context details\x02To view available contexts run " +
	"`%[1]s`\x02error: no context exists with the name: \x22%[1]v\x22\x02Disp" +
	"lay one or many endpoints from the sqlconfig file\x02List all the endpoi" +
	"nts in your sqlconfig file\x02Describe one endpoint in your sqlconfig fi" +
	"le\x02Endpoint name to view details of\x02Include endpoint details\x02To" +
	" view available endpoints run `%[1]s`\x02error: no endpoint exists with " +
	"the name: \x22%[1]v\x22\x02Display one or many users from the sqlconfig " +
	"file\x02List all the users in your sqlconfig file\x02Describe one user i" +
	"n your sqlconfig file\x02User name to view details of\x02Include user de" +
	"tails\x02To view available users run `%[1]s`\x02error: no user exists wi" +
	"th the name: \x22%[1]v\x22\x02Set the current context\x02Set the mssql c" +
	"ontext (endpoint/user) to be the current context\x02Name of context to s" +
	"et as current context\x02To run a query:    %[1]s\x02To remove:         " +
	"%[1]s\x02Switched to context \x22%[1]v\x22.\x02No context exists with th" +
	"e name: \x22%[1]v\x22\x02Display merged sqlconfig settings or a specifie" +
	"d sqlconfig file\x02Show sqlconfig settings, with REDACTED authenticatio" +
	"n data\x02Show sqlconfig settings and raw authentication data\x02Display" +
	" raw byte data\x02Install Azure Sql Edge\x02Install/Create Azure SQL Edg" +
	"e in a container\x02Tag to use, use get-tags to see list of tags\x02Cont" +
	"ext name (a default context name will be created if not provided)\x02Cre" +
	"ate a user database and set it as the default for login\x02Accept the SQ" +
	"L Server EULA\x02Generated password length\x02Minimum number of special " +
	"characters\x02Minimum number of numeric characters\x02Minimum number of " +
	"upper characters\x02Special character set to include in password\x02Don'" +
	"t download image.  Use already downloaded image\x02Line in errorlog to w" +
	"ait for before connecting\x02Specify a custom name for the container rat" +
	"her than a randomly generated one\x02Explicitly set the container hostna" +
	"me, it defaults to the container ID\x02Specifies the image CPU architect" +
	"ure\x02Specifies the image operating system\x02Port (next available port" +
	" from 1433 upwards used by default)\x02Download (into container) and att" +
	"ach database (.bak) from URL\x02Either, add the %[1]s flag to the comman" +
	"d-line\x04\x00\x01 6\x02Or, set the environment variable i.e. %[1]s %[2]" +
	"s=YES\x02EULA not accepted\x02--user-database %[1]q contains non-ASCII c" +
	"hars and/or quotes\x02Starting %[1]v\x02Created context %[1]q in \x22%[2" +
	"]s\x22, configuring user account...\x02Disabled %[1]q account (and rotat" +
	"ed %[2]q password). Creating user %[3]q\x02Start interactive session\x02" +
	"Change current context\x02View sqlcmd configuration\x02See connection st" +
	"rings\x02Remove\x02Now ready for client connections on port %[1]d\x02--u" +
	"sing URL must be http or https\x02%[1]q is not a valid URL for --using f" +
	"lag\x02--using URL must have a path to .bak file\x02--using file URL mus" +
	"t be a .bak file\x02Invalid --using file type\x02Creating default databa" +
	"se [%[1]s]\x02Downloading %[1]s\x02Restoring database %[1]s\x02Downloadi" +
	"ng %[1]v\x02Is a container runtime installed on this machine (e.g. Podma" +
	"n or Docker)?\x04\x01\x09\x00&\x02If not, download desktop engine from:" +
	"\x04\x02\x09\x09\x00\x03\x02or\x02Is a container runtime running?  (Try " +
	"`%[1]s` or `%[2]s` (list containers), does it return without error?)\x02" +
	"Unable to download image %[1]s\x02File does not exist at URL\x02Unable t" +
	"o download file\x02Install/Create SQL Server in a container\x02See all r" +
	"elease tags for SQL Server, install previous version\x02Create SQL Serve" +
	"r, download and attach AdventureWorks sample database\x02Create SQL Serv" +
	"er, download and attach AdventureWorks sample database with different da" +
	"tabase name\x02Create SQL Server with an empty user database\x02Install/" +
	"Create SQL Server with full logging\x02Get tags available for Azure SQL " +
	"Edge install\x02List tags\x02Get tags available for mssql install\x02The" +
	" -L parameter can not be used in combination with other parameters.\x02'" +
	"-a %#[1]v': Packet size has to be a number between 512 and 32767.\x02Ser" +
	"vers:\x02Legal docs and information: aka.ms/SqlcmdLegal\x02Third party n" +
	"otices: aka.ms/SqlcmdNotices\x04\x00\x01\x0a\x0e\x02Version %[1]v\x02Fla" +
	"gs:\x02-? shows this syntax summary, %[1]s shows modern sqlcmd sub-comma" +
	"nd help\x02Identifies one or more files that contain batches of SQL stat" +
	"ements. If one or more files do not exist, sqlcmd will exit. Mutually ex" +
	"clusive with %[1]s/%[2]s\x02Identifies the file that receives output fro" +
	"m sqlcmd\x02Print version information and exit\x02Implicitly trust the s" +
	"erver certificate without validation\x02This option sets the sqlcmd scri" +
	"pting variable %[1]s. This parameter specifies the initial database. The" +
	" default is your login's default-database property. If the database does" +
	" not exist, an error message is generated and sqlcmd exits\x02Uses a tru" +
	"sted connection instead of using a user name and password to sign in to " +
	"SQL Server, ignoring any environment variables that define user name and" +
	" password\x02Specifies the batch terminator. The default value is %[1]s" +
	"\x02The login name or contained database user name.  For contained datab" +
	"ase users, you must provide the database name option\x02Executes a query" +
	" when sqlcmd starts, but does not exit sqlcmd when the query has finishe" +
	"d running. Multiple-semicolon-delimited queries can be executed\x02Execu" +
	"tes a query when sqlcmd starts and then immediately exits sqlcmd. Multip" +
	"le-semicolon-delimited queries can be executed\x02%[1]s Specifies the in" +
	"stance of SQL Server to which to connect. It sets the sqlcmd scripting v" +
	"ariable %[2]s.\x02Disables commands that might compromise system securit" +
	"y. Sqlcmd issues a warning and continues\x02Specifies the SQL authentica" +
	"tion method to use to connect to Azure SQL Database. One of: ActiveDirec" +
	"toryDefault, ActiveDirectoryIntegrated, ActiveDirectoryPassword, ActiveD" +
	"irectoryInteractive, ActiveDirectoryManagedIdentity, ActiveDirectoryServ" +
	"icePrincipal, SqlPassword\x02Tells sqlcmd to use ActiveDirectory authent" +
	"ication. If no user name is provided, authentication method ActiveDirect" +
	"oryDefault is used. If a password is provided, ActiveDirectoryPassword i" +
	"s used. Otherwise ActiveDirectoryInteractive is used\x02Causes sqlcmd to" +
	" ignore scripting variables. This parameter is useful when a script cont" +
	"ains many %[1]s statements that may contain strings that have the same f" +
	"ormat as regular variables, such as $(variable_name)\x02Creates a sqlcmd" +
	" scripting variable that can be used in a sqlcmd script. Enclose the val" +
	"ue in quotation marks if the value contains spaces. You can specify mult" +
	"iple var=values values. If there are errors in any of the values specifi" +
	"ed, sqlcmd generates an error message and then exits\x02Requests a packe" +
	"t of a different size. This option sets the sqlcmd scripting variable %[" +
	"1]s. packet_size must be a value between 512 and 32767. The default = 40" +
	"96. A larger packet size can enhance performance for execution of script" +
	"s that have lots of SQL statements between %[2]s commands. You can reque" +
	"st a larger packet size. However, if the request is denied, sqlcmd uses " +
	"the server default for packet size\x02Specifies the number of seconds be" +
	"fore a sqlcmd login to the go-mssqldb driver times out when you try to c" +
	"onnect to a server. This option sets the sqlcmd scripting variable %[1]s" +
	". The default value is 30. 0 means infinite\x02This option sets the sqlc" +
	"md scripting variable %[1]s. The workstation name is listed in the hostn" +
	"ame column of the sys.sysprocesses catalog view and can be returned usin" +
	"g the stored procedure sp_who. If this option is not specified, the defa" +
	"ult is the current computer name. This name can be used to identify diff" +
	"erent sqlcmd sessions\x02Declares the application workload type when con" +
	"necting to a server. The only currently supported value is ReadOnly. If " +
	"%[1]s is not specified, the sqlcmd utility will not support connectivity" +
	" to a secondary replica in an Always On availability group\x02This switc" +
	"h is used by the client to request an encrypted connection\x02Specifies " +
	"the formatting for results\x02Controls which error messages are sent to " +
	"stdout. Messages that have severity level greater than or equal to this " +
	"level are sent\x02Level of mssql driver messages to print\x02Specifies t" +
	"hat sqlcmd exits and returns a %[1]s value when an error occurs\x02Contr" +
	"ols which error messages are sent to %[1]s. Messages that have severity " +
	"level greater than or equal to this level are sent\x02Specifies the numb" +
	"er of rows to print between the column headings. Use -h-1 to specify tha" +
	"t headers not be printed\x02Specifies that all output files are encoded " +
	"with little-endian Unicode\x02Specifies the column separator character. " +
	"Sets the %[1]s variable.\x02Remove trailing spaces from a column\x02Prov" +
	"ided for backward compatibility. Sqlcmd always optimizes detection of th" +
	"e active replica of a SQL Failover Cluster\x02Password\x02Controls the s" +
	"everity level that is used to set the %[1]s variable on exit\x02Specifie" +
	"s the screen width for output\x02Dedicated administrator connection\x02S" +
	"ets the sqlcmd scripting variable %[1]s\x02'%[1]s %[2]s': value must be " +
	"greater than or equal to %#[3]v and less than or equal to %#[4]v.\x02'%[" +
	"1]s %[2]s': value must be greater than %#[3]v and less than %#[4]v.\x02'" +
	"%[1]s %[2]s': Unexpected argument. Argument value has to be %[3]v.\x02'%" +
	"[1]s %[2]s': Unexpected argument. Argument value has to be one of %[3]v." +
	"\x02The %[1]s and the %[2]s options are mutually exclusive.\x02'%[1]s': " +
	"Missing argument. Enter '-?' for help.\x02'%[1]s': Unknown Option. Enter" +
	" '-?' for help.\x02Invalid variable identifier %[1]s\x02Invalid variable" +
	" value %[1]s"

var es_ESIndex = []uint32{ // 281 elements
	// Entry 0 - 1F
	0x00000000, 0x00000051, 0x00000077, 0x0000008b,
	0x000000a5, 0x00000109, 0x0000013a, 0x00000168,
	0x000001ab, 0x000001eb, 0x00000233, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	// Entry 20 - 3F
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	// Entry 40 - 5F
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	// Entry 60 - 7F
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	// Entry 80 - 9F
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	// Entry A0 - BF
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	// Entry C0 - DF
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	// Entry E0 - FF
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	// Entry 100 - 11F
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d, 0x0000025d, 0x0000025d, 0x0000025d,
	0x0000025d,
} // Size: 1148 bytes

const es_ESData string = "" + // Size: 605 bytes
	"\x02'-h %#[1]v': el valor de encabezado debe ser -1 o un valor entre -1 " +
	"y 2147483647\x02terminador de lote no válido '%[1]s'\x04\x00\x01 \x0f" +
	"\x02Sqlcmd: error:\x04\x00\x01 \x15\x02Sqlcmd: advertencia:\x02los coman" +
	"dos ED y !!<comando>, el script de inicio y las variables de entorno est" +
	"án deshabilitados\x02la variable de script '%[1]s' es de solo lectura" +
	"\x02No se definió la variable de script '%[1]s'.\x02la variable de entor" +
	"no '%[1]s' tiene un valor no válido: '%[2]s'.\x02error de sintaxis en la" +
	" línea %[1]d cerca del comando '%[2]s'.\x02%[1]s no se pudo abrir o actu" +
	"ar sobre el archivo %[2]s (motivo: %[3]s).\x02%[1]serror de sintaxis en " +
	"la línea %[2]d"

var fr_FRIndex = []uint32{ // 281 elements
	// Entry 0 - 1F
	0x00000000, 0x00000061, 0x0000008b, 0x000000a4,
	0x000000c3, 0x0000013b, 0x00000174, 0x000001ac,
	0x00000207, 0x00000253, 0x000002bf, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	// Entry 20 - 3F
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	// Entry 40 - 5F
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	// Entry 60 - 7F
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	// Entry 80 - 9F
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	// Entry A0 - BF
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	// Entry C0 - DF
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	// Entry E0 - FF
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	// Entry 100 - 11F
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3, 0x000002e3, 0x000002e3, 0x000002e3,
	0x000002e3,
} // Size: 1148 bytes

const fr_FRData string = "" + // Size: 739 bytes
	"\x02'-h %#[1]v': la valeur d'en-tête doit être\u00a0-1 ou une valeur com" +
	"prise entre\u00a0-1 et\u00a02147483647\x02terminateur de lot non valide " +
	"« %[1]s »\x04\x00\x01 \x14\x02Sqlcmd\u00a0: erreur\u00a0:\x04\x00\x01 " +
	"\x1a\x02Sqlcmd\u00a0: avertissement\u00a0\x02les commandes ED et !!<comm" +
	"ande>, ainsi que le script de démarrage et les variables d'environnement" +
	" sont désactivées\x02la variable de script «\u00a0%[1]s\u00a0» est en le" +
	"cture seule\x02La variable de script «\u00a0%[1]s\u00a0» n'est pas défin" +
	"ie.\x02la variable d'environnement «\u00a0%[1]s\u00a0» comporte une vale" +
	"ur non valide\u00a0: «\u00a0%[2]s\u00a0».\x02erreur de syntaxe à la lign" +
	"e %[1]d à côté de la commande «\u00a0%[2]s\u00a0».\x02%[1]s une erreur s" +
	"'est produite lors de l'ouverture ou de l'utilisation du fichier %[2]s (" +
	"Raison\u00a0: %[3]s).\x02erreur de syntaxe à la ligne %[2]d"

var it_ITIndex = []uint32{ // 281 elements
	// Entry 0 - 1F
	0x00000000, 0x0000005f, 0x00000087, 0x0000009c,
	0x000000b1, 0x0000010d, 0x00000142, 0x0000016f,
	0x000001b2, 0x000001f9, 0x00000246, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	// Entry 20 - 3F
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	// Entry 40 - 5F
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	// Entry 60 - 7F
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	// Entry 80 - 9F
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	// Entry A0 - BF
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	// Entry C0 - DF
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	// Entry E0 - FF
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	// Entry 100 - 11F
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e, 0x0000026e, 0x0000026e, 0x0000026e,
	0x0000026e,
} // Size: 1148 bytes

const it_ITData string = "" + // Size: 622 bytes
	"\x02'-h %#[1]v': il valore di intestazione deve essere -1 o un valore co" +
	"mpreso tra -1 e 2147483647\x02terminatore di batch non valido '%[1]s'" +
	"\x04\x00\x01 \x10\x02Sqlcmd: errore:\x04\x00\x01 \x10\x02Sqlcmd: avviso:" +
	"\x02i comandi ED e !!<command>, lo script di avvio e le variabili di amb" +
	"iente sono disabilitati\x02la variabile di scripting '%[1]s' è di sola l" +
	"ettura\x02Variabile di scripting '%[1]s' non definita.\x02la variabile d" +
	"i ambiente '%[1]s' ha un valore non valido: '%[2]s'.\x02errore di sintas" +
	"si alla riga %[1]d in prossimità del comando '%[2]s'.\x02%[1]s errore du" +
	"rante l'apertura o l'utilizzo del file %[2]s (motivo: %[3]s).\x02%[1]ser" +
	"rore di sintassi alla riga %[2]d"

var ja_JPIndex = []uint32{ // 281 elements
	// Entry 0 - 1F
	0x00000000, 0x0000006a, 0x0000009f, 0x000000b7,
	0x000000cc, 0x00000146, 0x0000018b, 0x000001ca,
	0x0000020d, 0x0000025a, 0x000002db, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	// Entry 20 - 3F
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	// Entry 40 - 5F
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	// Entry 60 - 7F
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	// Entry 80 - 9F
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	// Entry A0 - BF
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	// Entry C0 - DF
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	// Entry E0 - FF
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	// Entry 100 - 11F
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f, 0x0000030f, 0x0000030f, 0x0000030f,
	0x0000030f,
} // Size: 1148 bytes

const ja_JPData string = "" + // Size: 783 bytes
	"\x02'-h %#[1]v': ヘッダーには -1 または -1 から 2147483647 までの値を指定してください\x02バッチ ターミ" +
	"ネータ '%[1]s' は無効です\x04\x00\x01 \x13\x02Sqlcmd: エラー:\x04\x00\x01 \x10" +
	"\x02Sqlcmd: 警告:\x02ED コマンド、!!<command> コマンド、スタートアップ スクリプト、および環境変数が無効です" +
	"\x02エラー: スクリプト変数 '%[1]s' は読み取り専用です\x02'%[1]s' スクリプト変数が定義されていません。\x02環境変数" +
	" '%[1]s' には無効な値 '%[2]s' があります。\x02行 %[1]d のコマンド '%[2]s' 付近に構文エラーがあります。" +
	"\x02%[1]s ファイル %[2]s を開くときか、このファイルの処理中にエラーが発生しました (理由: %[3]s)。\x02%[1]s行" +
	" %[2]d に構文エラーがあります。"

var ko_KRIndex = []uint32{ // 281 elements
	// Entry 0 - 1F
	0x00000000, 0x0000005c, 0x00000088, 0x0000009d,
	0x000000b2, 0x00000110, 0x0000014b, 0x00000188,
	0x000001c9, 0x00000217, 0x0000028b, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	// Entry 20 - 3F
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	// Entry 40 - 5F
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	// Entry 60 - 7F
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	// Entry 80 - 9F
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	// Entry A0 - BF
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	// Entry C0 - DF
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	// Entry E0 - FF
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	// Entry 100 - 11F
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4, 0x000002c4, 0x000002c4, 0x000002c4,
	0x000002c4,
} // Size: 1148 bytes

const ko_KRData string = "" + // Size: 708 bytes
	"\x02'-h %#[1]v': 헤더 값은 -1이거나 -1에서 2147483647 사이의 값이어야 합니다\x02잘못된 일괄 처리 종" +
	"결자 ''%[1]s''\x04\x00\x01 \x10\x02Sqlcmd: 오류:\x04\x00\x01 \x10\x02Sqlcm" +
	"d: 경고:\x02ED 및 !!<명령> 명령, 시작 스크립트 및 환경 변수는 사용할 수 없습니다\x02스크립팅 변수 '%[1]s'" +
	"은(는) 읽기 전용입니다\x02'%[1]s' 스크립팅 변수가 정의되지 않았습니다.\x02환경 변수 '%[1]s'에 잘못된 값이" +
	" 있습니다: '%[2]s'.\x02명령 '%[2]s' 근처의 줄 %[1]d에서 구문 오류가 발생했습니다.\x02%[1]s 파일 %" +
	"[2]s을(를) 열거나 해당 작업을 수행하는 중 오류가 발생했습니다(원인: %[3]s).\x02%[1]s줄 %[2]d에서 구문 오" +
	"류가 발생했습니다"

var pt_BRIndex = []uint32{ // 281 elements
	// Entry 0 - 1F
	0x00000000, 0x00000050, 0x00000075, 0x00000088,
	0x0000009c, 0x00000107, 0x0000013a, 0x00000165,
	0x000001a7, 0x000001e3, 0x0000022e, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	// Entry 20 - 3F
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	// Entry 40 - 5F
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	// Entry 60 - 7F
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	// Entry 80 - 9F
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	// Entry A0 - BF
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	// Entry C0 - DF
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	// Entry E0 - FF
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	// Entry 100 - 11F
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252, 0x00000252, 0x00000252, 0x00000252,
	0x00000252,
} // Size: 1148 bytes

const pt_BRData string = "" + // Size: 594 bytes
	"\x02'-h %#[1]v': o valor do cabeçalho deve ser -1 ou um valor entre 1 e " +
	"2147483647\x02terminador de lote inválido '%[1]s'\x04\x00\x01 \x0e\x02Sq" +
	"lcmd: erro:\x04\x00\x01 \x0f\x02Sqlcmd: aviso:\x02os comandos ED e !!<co" +
	"mando>, o script de inicialização e as variáveis de ambiente estão desab" +
	"ilitados\x02a variável de script: '%[1]s' é somente leitura.\x02Variável" +
	" de script '%[1]s' não definida.\x02a variável de ambiente: '%[1]s' poss" +
	"ui valor inválido: '%[2]s'.\x02erro de sintaxe na linha %[1]d próximo ao" +
	" comando '%[2]s'.\x02%[1]s ocorreu um erro ao abrir ou operar no arquivo" +
	" %[2]s (Motivo: %[3]s).\x02%[1]serro de sintaxe na linha %[2]d"

var ru_RUIndex = []uint32{ // 281 elements
	// Entry 0 - 1F
	0x00000000, 0x00000080, 0x000000c8, 0x000000e4,
	0x00000103, 0x00000183, 0x000001e2, 0x00000229,
	0x00000291, 0x00000305, 0x00000374, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	// Entry 20 - 3F
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	// Entry 40 - 5F
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	// Entry 60 - 7F
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	// Entry 80 - 9F
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	// Entry A0 - BF
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	// Entry C0 - DF
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	// Entry E0 - FF
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	// Entry 100 - 11F
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9, 0x000003b9, 0x000003b9, 0x000003b9,
	0x000003b9,
} // Size: 1148 bytes

const ru_RUData string = "" + // Size: 953 bytes
	"\x02'-h %#[1]v': значением заголовка может быть или -1, или число между " +
	"-1 и 2147483647\x02недопустимый признак конца пакета '%[1]s'\x04\x00\x01" +
	" \x17\x02Sqlcmd: ошибка -\x04\x00\x01 \x1a\x02Sqlcmd: внимание!\x02ED, а" +
	" также команды !!<command>, скрипт запуска и переменные среды отключены" +
	"\x02переменная скрипта: '%[1]s' доступна только для чтения\x02Переменная" +
	" скрипта '%[1]s' не определена.\x02переменная среды: '%[1]s' имеет недоп" +
	"устимое значение: '%[2]s'.\x02синтаксическая ошибка в строке %[1]d при " +
	"выполнении команды '%[2]s'.\x02%[1]s ошибка при открытии или обработке " +
	"файла %[2]s (причина: %[3]s).\x02%[1]sсинтаксическая ошибка в строке %[" +
	"2]d"

var zh_CNIndex = []uint32{ // 281 elements
	// Entry 0 - 1F
	0x00000000, 0x0000004e, 0x00000071, 0x00000086,
	0x0000009b, 0x000000db, 0x000000fe, 0x0000011e,
	0x00000146, 0x0000017f, 0x000001c9, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	// Entry 20 - 3F
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	// Entry 40 - 5F
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	// Entry 60 - 7F
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	// Entry 80 - 9F
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	// Entry A0 - BF
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	// Entry C0 - DF
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	// Entry E0 - FF
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	// Entry 100 - 11F
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee, 0x000001ee, 0x000001ee, 0x000001ee,
	0x000001ee,
} // Size: 1148 bytes

const zh_CNData string = "" + // Size: 494 bytes
	"\x02'-h %#[1]v': 标头值必须是 -1 或是介于 1 和 2147483647 之间的值\x02无效的批处理终止符'%[1]s'" +
	"\x04\x00\x01 \x10\x02Sqlcmd: 错误:\x04\x00\x01 \x10\x02Sqlcmd: 警告:\x02ED 和" +
	" !!<命令> 命令、启动脚本和环境变量被禁用\x02脚本变量'%[1]s'是只读的。\x02未定义'%[1]s'脚本变量。\x02环境变量'%" +
	"[1]s'的值无效:'%[2]s'\x02命令'%[2]s'附近的第 %[1]d 行存在语法错误。\x02%[1]s 打开文件 %[2]s 或对" +
	"其执行操作时出错(原因: %[3]s)。\x02%[1]s第 %[2]d 行存在语法错误"

var zh_TWIndex = []uint32{ // 281 elements
	// Entry 0 - 1F
	0x00000000, 0x0000004c, 0x0000006e, 0x00000083,
	0x00000098, 0x000000dd, 0x00000100, 0x00000125,
	0x00000154, 0x0000018f, 0x000001d4, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	// Entry 20 - 3F
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	// Entry 40 - 5F
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	// Entry 60 - 7F
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	// Entry 80 - 9F
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	// Entry A0 - BF
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	// Entry C0 - DF
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	// Entry E0 - FF
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	// Entry 100 - 11F
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9, 0x000001f9, 0x000001f9, 0x000001f9,
	0x000001f9,
} // Size: 1148 bytes

const zh_TWData string = "" + // Size: 505 bytes
	"\x02'-h %#[1]v': 標頭值必須是 -1 或介於 -1 和 2147483647 之間的值\x02批次結束字元 '%[1]s' 無效" +
	"\x04\x00\x01 \x10\x02Sqlcmd: 錯誤:\x04\x00\x01 \x10\x02Sqlcmd: 警告:\x02已停用 " +
	"ED 和 !!<command> 命令、啟動指令碼和環境變數\x02指令碼變數: '%[1]s' 為唯讀\x02未定義 '%[1]s' 指令碼變" +
	"數。\x02環境變數: '%[1]s' 有無效值: '%[2]s'。\x02第 %[1]d 行接近命令 '%[2]s' 之處有語法錯誤。" +
	"\x02%[1]s 開啟或操作檔案 %[2]s 時發生錯誤 (原因: %[3]s)。\x02%[1]s第 %[2]d 行有語法錯誤。"

	// Total table size 34073 bytes (33KiB); checksum: 87DD1035
