name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  golangci-pr:
    name: lint-pr-changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v6
        with:
          go-version: '1.24'
      - uses: actions/checkout@v6
      - name: golangci-lint
        uses: 1e7e51e771db61008b38414a730f564565cf7c20 # v9
        with:
          only-new-issues: true
