name: Submit published release to WinGet community repository

on:
  release:
    types: [published]

jobs:
  publish-winget:
    name: Submit to WinGet repository
    # winget-create is only supported on Windows
    runs-on: windows-latest
    permissions:
      contents: read
    env:
      # winget-create will read the following environment variable to access the GitHub token needed for submitting a PR
      # See https://aka.ms/winget-create-token
      WINGET_CREATE_GITHUB_TOKEN: ${{ secrets.WINGET_CREATE_GITHUB_TOKEN }}
    # Only submit stable releases
    if: ${{ !github.event.release.prerelease }}
    steps:
      - name: Submit package using wingetcreate
        run: |
          # Get installer info from release event
          $assets = '${{ toJSON(github.event.release.assets) }}' | ConvertFrom-Json
          $x64InstallerUrl = $assets | Where-Object -Property name -eq 'sqlcmd-amd64.msi' | Select-Object -ExpandProperty browser_download_url
          $arm64InstallerUrl = $assets | Where-Object -Property name -eq 'sqlcmd-arm64.msi' | Select-Object -ExpandProperty browser_download_url
          $packageVersion = (${{ toJSON(github.event.release.tag_name) }}).Trim('v')

          # Update package using wingetcreate
          curl.exe -JLO https://aka.ms/wingetcreate/latest
          .\wingetcreate.exe update Microsoft.Sqlcmd `
            --version $packageVersion `
            --urls $x64InstallerUrl $arm64InstallerUrl `
            --submit
